// import "./globals.css"
// import Header from "@/components/Header"
// import Footer from "@/components/Footer"
// import { AuthProvider } from "@/context/AuthContext"
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <Header /> <AuthProvider>{children} </AuthProvider>
//         <Footer />
//       </body>
//     </html>
//   )
// }
import "./globals.css"
import { AuthProvider } from "@/context/AuthContext"
import Header from "@/components/Header"
import Footer from "@/components/Footer"

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <AuthProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}
